development: &base
    app_id: 111159975701312
    secret_key: 4444af97c4577a0cfc7d770b0b5f3072
    callback: "http://dev.wafflestudio.net:4011/signin/facebook"
test:
  <<: *base
production:
  <<: *base
